version: '3.8'

services:
  bosques-riparios:
    image: adaghost/bosques-riparios:latest
    container_name: dashboard-bosques-riparios
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
    networks:
      - dashboard-network

  huella-humana:
    image: adaghost/huella-humana:latest
    container_name: dashboard-huella-humana
    ports:
      - "8002:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge